### ISSUE TITLE
item中多Edittext会出现数据混乱的情况，设置addTextChangedListener

### ISSUE THREAD

**Issue by LikCodeLab** [bingoogolapple/BGAAdapter-Android#14]

**Comment by bingoogolapple** [comment]
不是这个库的问题，是你 Android 基础知识扎实的问题，建议你把 EditText 添加到单独的界面里 addTextChangedListener 后，再在代码里动态改变 EditText 的内容，看下 onTextChanged 里打印日志的情况，这时候你就明白了，然后再在网上搜索怎样解决吧

**Comment by LikCodeLab** [comment]
我的意思是否提供一种方法机制来直接解决
RecyclerView中的Item中有EditText，同时我们需要对EditText增加输入监听的情况出现的问题：
    我们在滑动的时候，其他行的EditText会莫名地调用addTextChangedListener，这个时候，我们的position不能用，onBindViewHolder的position来获取，list中的元素，因为此时的position是不固定的，也就是说list.get(position),这个拿到的object也是不固定的

**Comment by bingoogolapple** [comment]
网上有解决方案的，但是这个问题不是 BGAAdapter-Android 该解决的事情，你需要你自己增加一个状态码来表示当前是否在执行 getView 方法，如果是的话就在 addTextChangedListener 里忽略这次改变事件。

另一种方法就是通过 ImageView 或者 Button 来做，自己替换背景。

本来上上条回复的目的是让你自己到网上寻找解决方案，结果还是倒回来问！
