### ISSUE TITLE
listindexview 中最后一项看不到，或者被遮挡

### ISSUE THREAD

**Issue by cooliean** [bingoogolapple/BGAAdapter-Android#2]
如题

**Comment by bingoogolapple** [comment]
@cooliean 是ListView、GridView和CoordinatorLayout、AppBarLayout结合使用时导致的，没支持layout_scrollFlags，使用BaseAdapter和CursorAdapter也会有这个问题。建议使用RecyclerView

**Comment by cooliean** [comment]
好的，谢谢了
