### ISSUE TITLE
混淆

### ISSUE THREAD

**Issue by hanxiaozhe** [bingoogolapple/BGAAdapter-Android#26]
建议可以贴出混淆配置来下。

**Comment by bingoogolapple** [comment]
这个库不用配置混淆规则

**Comment by REBOOTERS** [comment]
关于混淆配置，还是有点疑问，不知道是不是升级到Android Studio 3.0 的问题

**环境：**
Android Studio 3.0 

gradle 配置 (摘选重要信息）

distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

```
dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
compileSdkVersion 26
buildToolsVersion "26.0.2"

dependencies {
    compile 'com.android.support:recyclerview-v7:26.0.1'
    compile 'cn.bingoogolapple:bga-baseadapter:1.2.6@aar'
    compile 'com.jakewharton:butterknife:8.8.1'
    .......
}
```
 minifyEnabled true  后有如下

**报错信息**

Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class android.databinding.DataBindingUtil
Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class cn.bingoogolapple.baseadapter.BR
Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class android.databinding.ViewDataBinding
Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class cn.bingoogolapple.baseadapter.BR
Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class android.databinding.ViewDataBinding
Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class android.databinding.DataBindingUtil
Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class cn.bingoogolapple.baseadapter.BR
Warning:cn.bingoogolapple.baseadapter.BGABindingRecyclerViewAdapter: can't find referenced class android.databinding.ViewDataBinding
Warning:cn.bingoogolapple.baseadapter.BGABindingViewHolder: can't find referenced class android.databinding.ViewDataBinding
Warning:cn.bingoogolapple.baseadapter.BGAViewBindingAdapter: can't find referenced class android.databinding.BindingAdapter

导致无法正常打包，看到上面说不需要配置混淆，所以有些疑惑，到底是否需要进行Proguard 配置。

**Comment by hanxiaozhe** [comment]
DataBinding 需要加入混淆吧

**Comment by REBOOTERS** [comment]
嗯，DataBindding 是由jakewharton:butterknife 插件产生的中间类，经过自己测试发现，使用butterknife时的确是需要添加混淆的，正常的findViewById 是可以不加的。
