### ISSUE TITLE
使用该适配器设置嵌套ListView问题

### ISSUE THREAD

**Issue by yummyChina** [bingoogolapple/BGAAdapter-Android#6]
你好，在尝试使用您的适配器库 加载嵌套ListView时，对ViewHolderHelper扩充了一点设置子ListView的方法如下：
/**
     *
     \* @param viewId
     \* @return
     */
    public BGAViewHolderHelper setChildListView(@IdRes int viewId){
        childListView = (ListView) getView(viewId);
        return  this;
    }

```
/**
 * @param childListViewAdapter
 * @return
 */
public BGAViewHolderHelper setChildListViewAdapter(BGAAdapterViewAdapter childListViewAdapter){
    this.childListView.setAdapter(childListViewAdapter);
    return this;
}

/**
 * 设置子listView 的selector
 * @param drawable
 * @return
 */
public BGAViewHolderHelper setChildListViewSelector(Drawable drawable){
    this.childListView.setSelector(drawable);
    return this;
}

public BGAViewHolderHelper setChildListViewDivider(Drawable divider){
    this.childListView.setDivider(divider);
    return this;
}

public BGAViewHolderHelper setChildListViewDividerHeight(int height){
    this.childListView.setDividerHeight(height);
    return this;
}

/**
 * 在存在子ListView的情况下，子listview填充完数据之后 重新计算父listview高度
 * @return
 */
public BGAViewHolderHelper resetListViewHeight(){
    ViewUtil.setListViewHeightBasedOnChildren(this.childListView);
    return this;
}
```

在fillData里设置子ListVIew相关信息：
@Override
    protected void fillData(BGAViewHolderHelper viewHolderHelper, int position, Order model) {
        viewHolderHelper.setText(R.id.orderNum,model.getNumber());
        viewHolderHelper.setText(R.id.orderType,model.getType());
        viewHolderHelper.setText(R.id.custName,model.getUserName());
        viewHolderHelper.setText(R.id.custPhone,model.getUserPhone());
        viewHolderHelper.setText(R.id.custAddress,model.getUserAddress());
        viewHolderHelper.setText(R.id.deliTime, model.getDeliTime());
        viewHolderHelper.setText(R.id.deliStatus,model.getDeliStatus());

```
    _goodsAdapter = new GoodsAdapterTest(_context);//也是继承自BAGAdatperViewAdapter
    _goodsAdapter.setDatas(model.getGoods());
    viewHolderHelper.setChildListView(R.id.goods_list)
             .setChildListViewAdapter(_goodsAdapter)
```

//                 .setChildListViewSelector(new ColorDrawable(Color.WHITE))
                 .setChildListViewDivider(new ColorDrawable(Color.WHITE))
                 .setChildListViewDividerHeight(1)
                 .resetListViewHeight();
    }现在的疑问是 如何把子ListView的item点击事件 传递到activity,因为子ListView需要多个adapter，直接把_goodsAdapter透给activity行不通，有什么建议吗

**Comment by bingoogolapple** [comment]
@yummyChina ListView嵌套ListView时，建议把嵌套的ListView封装成自定义控件，可以参考 [BGAPhotoPicker-Android](https://github.com/bingoogolapple/BGAPhotoPicker-Android) 中的 BGANinePhotoLayout
